name: xnew

on:
  workflow_dispatch:
    inputs:
      pkgname:
        description: "pkg name"
        required: true
        default: "defaultpkg"

jobs:
  generate:
    runs-on: ubuntu-latest
    container: voidlinux/voidlinux:latest
    env:
      SSL_NO_VERIFY_PEER: "1"

    steps:
      - name: Fix mirror
        run: |
          sed -i 's|https://alpha.de.repo.voidlinux.org|https://repo.voidlinux.org|g' /usr/share/xbps.d/*.conf
          echo "=== /usr/share/xbps.d/ ==="
          cat /usr/share/xbps.d/*.conf

      - name: Install deps
        run: xbps-install -Syu ca-certificates libstdc++

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install xtools
        run: xbps-install -Syu xtools

      - name: xnew
        run: |
          xnew ${{ inputs.pkgname }}
          echo "---"
          cat srcpkgs/${{ inputs.pkgname }}/template

      - name: Upload template
        uses: actions/upload-artifact@v4
        with:
          name: template
          path: srcpkgs/${{ inputs.pkgname }}/
